version: '3'

services:
  jenkins_db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      jenkins_network:
        ipv4_address: 192.168.1.10

  jenkins:
    build: .
    privileged: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      jenkins_network:
        ipv4_address: 192.168.1.2

networks:
  jenkins_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
